name: palet_sayim_new
description: "A new Flutter project for Palet Sayim"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.2
  animations: ^2.0.11
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.41
  pdf: ^3.10.4
  printing: ^5.11.0
  fl_chart: ^0.65.0
  open_filex: ^4.3.2
  audioplayers: ^6.0.0
  image: ^4.5.4
  esc_pos_utils_plus: ^2.0.4
  permission_handler: ^12.0.1
  print_bluetooth_thermal: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/avatars/
